// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc172.NorthernForce.subsystems;

import org.usfirst.frc172.NorthernForce.RobotMap;
import org.usfirst.frc172.NorthernForce.commands.*;
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Ultrasonic;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveBase extends Subsystem 
{

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private static final CANTalon talon1 = RobotMap.driveBaseCANTalon1;
    private static final CANTalon talon2 = RobotMap.driveBaseCANTalon2;
    private static final CANTalon talon3 = RobotMap.driveBaseCANTalon3;
    private static final CANTalon talon4 = RobotMap.driveBaseCANTalon4;
    private static final CANTalon talon5 = RobotMap.driveBaseCANTalon5;
    private static final CANTalon talon6 = RobotMap.driveBaseCANTalon6;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static RobotDrive driveSet1;
    public static RobotDrive driveSet2;		//Motor Set 2 (same position on left and right)
    public static RobotDrive driveSet3;		//Motor Set 3 (same position on left and right)

    {
    driveSet1 = new RobotDrive(talon1, talon2);
    driveSet1.setSafetyEnabled(true);
    driveSet1.setExpiration(0.1);
    driveSet1.setSensitivity(0.5);
    driveSet1.setMaxOutput(1.0);

    driveSet2 = new RobotDrive(talon3, talon4);
    driveSet2.setSafetyEnabled(true);
    driveSet2.setExpiration(0.1);
    driveSet2.setSensitivity(0.5);
    driveSet2.setMaxOutput(1.0);

    driveSet3 = new RobotDrive(talon5, talon6);
    driveSet3.setSafetyEnabled(true);
    driveSet3.setExpiration(0.1);
    driveSet3.setSensitivity(0.5);
    driveSet3.setMaxOutput(1.0);
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    }
    
    public void initDefaultCommand() 
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        ;
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    


}

