// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc172.NorthernForce;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Ultrasonic;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveBaseCANTalon1;
    public static CANTalon driveBaseCANTalon2;
    public static CANTalon driveBaseCANTalon3;
    public static CANTalon driveBaseCANTalon4;
    public static CANTalon driveBaseCANTalon5;
    public static CANTalon driveBaseCANTalon6;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static Ultrasonic ultrasonicSensor;
    



    //RoboRio Port Assignments
    
    public static final int CANTalon1 = 0;		//CAN Talon #1 Address -- Left  Drive Set 1
    public static final int CANTalon2 = 1;		//CAN Talon #2 Address -- Right Drive Set 1
    public static final int CANTalon3 = 2;		//CAN Talon #3 Address -- Left  Drive Set 2
    public static final int CANTalon4 = 3;		//CAN Talon #4 Address -- Right Drive Set 2
    public static final int CANTalon5 = 4;		//CAN Talon #5 Address -- Left  Drive set 3
    public static final int CANTalon6 = 5;		//CAN Talon #6 Address -- Right Drive Set 3
    
    public static final int digitalPingPort = 1; //"Ping" (sample) Digital Port for Ultrasonic Range Finder
    public static final int analogEchoPort  = 1; //"Echo" (read)   Analog Port for Ultrasonic Range Finder
    
    public static final int joyStickPort = 0;	 //Joystick 
    
    
    //End of Port assignments
    

    public static void init() {

        driveBaseCANTalon1 = new CANTalon(CANTalon1);
        LiveWindow.addActuator("DriveBase", "CAN Talon 1", driveBaseCANTalon1);
        driveBaseCANTalon2 = new CANTalon(CANTalon2);
        LiveWindow.addActuator("DriveBase", "CAN Talon 2", driveBaseCANTalon2);
        driveBaseCANTalon3 = new CANTalon(CANTalon3);
        LiveWindow.addActuator("DriveBase", "CAN Talon 3", driveBaseCANTalon3);
        driveBaseCANTalon4 = new CANTalon(CANTalon4);     
        LiveWindow.addActuator("DriveBase", "CAN Talon 4", driveBaseCANTalon4);
        driveBaseCANTalon4 = new CANTalon(CANTalon5);     
        LiveWindow.addActuator("DriveBase", "CAN Talon 5", driveBaseCANTalon4);
        driveBaseCANTalon4 = new CANTalon(CANTalon6);     
        LiveWindow.addActuator("DriveBase", "CAN Talon 6", driveBaseCANTalon4);
        
        ultrasonicSensor = new Ultrasonic(digitalPingPort, analogEchoPort);
        
//        driveSet1 = new RobotDrive(driveBaseCANTalon1, driveBaseCANTalon2);
//        driveSet1.setSafetyEnabled(true);
//        driveSet1.setExpiration(0.1);
//        driveSet1.setSensitivity(0.5);
//        driveSet1.setMaxOutput(1.0);
//
//        driveSet2 = new RobotDrive(driveBaseCANTalon3, driveBaseCANTalon4);
//        driveSet2.setSafetyEnabled(true);
//        driveSet2.setExpiration(0.1);
//        driveSet2.setSensitivity(0.5);
//        driveSet2.setMaxOutput(1.0);
//
//        driveSet3 = new RobotDrive(driveBaseCANTalon5, driveBaseCANTalon6);
//        driveSet3.setSafetyEnabled(true);
//        driveSet3.setExpiration(0.1);
//        driveSet3.setSensitivity(0.5);
//        driveSet3.setMaxOutput(1.0);


    }
}
